### ISSUE TITLE
Actions columns in double

### ISSUE THREAD

**Issue by msi2** [escaped/django-inline-actions#1]
Hi, thank you for this app, i was looking for something like that for months !

When I add what needed (like the doc), I have two action columns with same buttons.

Any clue ?

**Comment by escaped** [comment]
Hey,
that's strange. There is even a [test that should cover this case](https://github.com/escaped/django-inline-actions/commit/8fefd884a0c54d53b77616bca772fff5a0e8ff8d#diff-d603b2ab05bbcf5c8ece448946ad4ea8R54).

Could you please provide some more information about your environment? e.g. Django version, do you use additional extensions for your `AdminModel`?

**Comment by escaped** [comment]
This should be fixed. Thanks to @torwald-sergesson (#2)
