### ISSUE TITLE
Django 2.1 compatibility

### ISSUE THREAD

**Issue by zacbri** [escaped/django-inline-actions#13]
Current setup.py prevents using your package with Django 2.1.  
Are there any technical reasons (perhaps I could push a PR to help with that)?  

If not could you release a new version with updated dependencies please?  
Thanks

**Comment by escaped** [comment]
Thanks for the hint. I just updated the compatibility matrix and pushed a new version to pypi.

**Comment by zacbri** [comment]
Awesome, thanks!
