### ISSUE TITLE
Error: ActionNotCallable on using InlineActionsModelAdminMixin action

### ISSUE THREAD

**Issue by belek** [escaped/django-inline-actions#18]
Hi, thanks for this lib, very helpful!

I have a ModelAdmin class for my News model, without inlines, so I used InlineActionsModelAdminMixin and wrote an action to publish or unpublish news:
```
from inline_actions.admin import InlineActionsModelAdminMixin
class CustomerNewsAdmin(InlineActionsModelAdminMixin, admin.ModelAdmin):
    list_display = ('title', 'city', 'body', 'published', 'notified')
    inline_actions = ['toggle_publish']

    def toggle_publish(self, request, obj):
        if obj.published:
            obj.published = False
        else:
            obj.published = True
        obj.save()
        messages.success(request, "News successfully published!")
        return True
```
When I click on action button I see an error:
![Screen Shot 2019-03-26 at 13 18 12](https://user-images.githubusercontent.com/5576684/54978174-b37f5c80-4fc9-11e9-963c-555780628655.png)
![Screen Shot 2019-03-26 at 13 19 12](https://user-images.githubusercontent.com/5576684/54978201-c4c86900-4fc9-11e9-8044-47e81d99d194.png)

In order to get rid of that error I had to specify `parent_obj=None`:
```def toggle_publish(self, request, obj, parent_obj=None):```
But the docs clearly says:
> parent_obj - instance of the parent model, only set on inlines

So I guess there are some not properly working checks on `parent_obj` attribute that leads to an error for InlineActionsModelAdminMixin usage without inlines.

**Comment by escaped** [comment]
Hi @belek,

I am glad, that you like my little lib :)  ...The given behaviour is intended, as I wanted to keep the API (signature of an action) for the `ModelAdmin` and the `InlineAdmin` the same. Therefore it is required to add `parent_obj=None` even though it will be `None` all the time.

But I guess I could improve the error message and improve the documentation a bit.

**Comment by escaped** [comment]
Update the wording of the documentation and used `raise from` (5055659) to no swallow the original exception.
