### ISSUE TITLE
How to test actions?

### ISSUE THREAD

**Issue by belek** [escaped/django-inline-actions#19]
I wonder how to write tests on actions code?
I inspected request and see a POST requests with following data:
>csrfmiddlewaretoken=weqACxEtdnCNw4JCsJPZKGuI7eQ8whgSfMzEqNX6npgXgwkNjrYFeNfolKga1SfR&action=&select_across=0&_action__admin__toggle_publish__news__customernews__2=Unpublish

Is there any way to write a test on action except simulating POST request with above fields?

**Comment by escaped** [comment]
You can basically copy the tests, I have written for the `test_proj`. You can find the code [here]( https://github.com/escaped/django-inline-actions/blob/master/test_proj/blog/tests/test_inline_admin.py#L146).
It basically emulates the user and makes sure the actions are rendered as expected.

If you just want to test the action itself, you could do something like:
```
@pytest.fixture
def admin_site():
    return AdminSite()


@pytest.mark.django_db
def test_action_XXX(admin_site):
    """Test action XXX"""
    fake_request = {}  # you might need to use a RequestFactory here
    obj = ...

    admin = MyAdmin(obj, admin_site)

    admin.render_inline_actions(article)
    response = admin.action_XXX(fake_request, obj)
    # assert the state of the application
```

I hope that helps.

**Comment by escaped** [comment]
I guess I should add a small section about testing to the README. Thanks for pointing that out :)

**Comment by belek** [comment]
Thanks, that makes things clear!
Yes, would be helpful to have it in docs.

**Comment by escaped** [comment]
Added a small section to the README :)
