### ISSUE TITLE
Support for Django 2.2

### ISSUE THREAD

**Issue by alexandernst** [escaped/django-inline-actions#20]
Django 2.2 changed some admin-related stuff. Is this lib compatible with Django 2.2?

**Comment by escaped** [comment]
I quickly updated the test suite (#21) and it seems that there are no issues with Django 2.2. But I need to mention, that I haven't manually tested the plugin yet. If you are eager to test it yourself, feel free to give it a go :)

**Comment by escaped** [comment]
My changes have been merged to master and I will release them shortly :)
