### ISSUE TITLE
Actions for new inline rows?

### ISSUE THREAD

**Issue by AlanL-django** [escaped/django-inline-actions#42]
Is it possible to have actions for new rows that I have just added to a TabularInline in the front end, that don't yet exist in the database? Could I make an ajax call to the back end that would call get_inline_actions and trigger a refresh of my template?

Apologies if the answer to this is obvious - I am mostly a back end developer and profoundly ignorant of everything that goes on in the front end world of templates / css / javascript

**Comment by escaped** [comment]
mmh... I don't think this will work as - as you mentioned - the object is only created once you save the page. Beforehand you only see the form with the values and even if the buttons were already available, there would be no object in the database which we could modify. :/  so... I guess, no it's not possible without some ugly hacks.

**Comment by AlanL-django** [comment]
Yeah, thanks, that's more or less what I suspected.
