### ISSUE TITLE
The file 'inline_actions/css/inline_actions.css' could not found when using S3 Manifest Storage

### ISSUE THREAD

**Issue by tsantor** [escaped/django-inline-actions#45]
The static assets for this package do not get collected properly when running `collectstatic`.  When using manifest storage it causes an error `The file 'inline_actions/css/inline_actions.css' could not found`. The only way around this is to upload the missing CSS file manually to the bucket.

**Note:** Even running `collectstatic` on local development machine (just to see what gets collected) the static assets are not collected for this package.

**Comment by merwok** [comment]
Is the app in INSTALLED_APPS?

**Comment by tsantor** [comment]
Man I feel dumb, the one place I didn't check. Case closed.
