### ISSUE TITLE
Overriding get_readonly_fields while using InlineActionsModelAdminMixin causes valueError

### ISSUE THREAD

**Issue by raiyankamal** [escaped/django-inline-actions#5]
The error occurs at this line: https://github.com/escaped/django-inline-actions/blob/master/inline_actions/admin.py#L185

**Comment by escaped** [comment]
I don't know why the field list is empty, but the error should be easy to resolve with a simple `try: catch ValueError`. It would be nice to have a minimal testcase for that: Under which circumstances did the error occure?

**Comment by escaped** [comment]
The package is used by quite a lot of people and no one else experience this problem. For now, I am closing this issue until it comes up again.
