### ISSUE TITLE
With Django >= 4.x change ugettext_lazy to gettext_lazy. 

### ISSUE THREAD

**Issue by dhiashalabi** [escaped/django-inline-actions#52]
Chnage ugettext_lazy to gettext_lazy in `inline_actions/admin.py`.

**Comment by earthcomfy** [comment]
Hi @dhiaaalshalabi, I would love to work on this if it's still up.

**Comment by dhiashalabi** [comment]
> Hi @dhiaaalshalabi, I would love to work on this if it's still up.

The issue has been resolved by @Ivan-Feofanov using PR #43.
